


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.182.128:3306/gulimall_wms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  application:
    name: gulimall-ware
  jackson:
    date-format: yyyy/MM/dd HH:mm:ss
    time-zone: GMT+8

  main:
    allow-circular-references: true
  rabbitmq:
    host: 192.168.182.128
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual




server:
  port: 300

mybatis-plus:
  global-config:
    db-config:
      id-type: auto






#seata:
#  tx-service-group: gulimall-ware
#  service:
#    vgroup-mapping:
#      gulimall-ware: default
#  config:
#    type: nacos
#    nacos:
#      namespace: seata
#      server-addr: 192.168.182.128:8848
#      username: nacos
#      password: nacos
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 192.168.182.128:8848
#      username: nacos
#      password: nacos
#      cluster: default
#      namespace: public