spring:
  application:
    name: auth-server
  thymeleaf:
    cache: false
  redis:
    host: 192.168.182.128
    port: 6379
  session:
    store-type: redis
    timeout: 50m
  main:
    allow-circular-references: true

server:
  port: 700







