spring:
  application:
    name: auth-server
  thymeleaf:
    cache: false
  redis:
    host: 192.168.182.128
    port: 6379
  session:
    store-type: redis
    timeout: 30m

server:
  port: 700








