spring:
  cloud:
    gateway:
      routes:
        #        路由规则名字
        - id: test
          #          路由地址
          uri: http://www.baidu.com
          #          断言，查看是否满足，满足则路由到相应地址
          predicates:
            #          url为路由地址 baidu为携带参数，若携带参数有则路由
            - Query=url,baidu

        - id: product
          uri: lb://gulimall-product
          predicates:
              - Path=/api/product/**,/hello
          filters:
              - RewritePath=/api(?<segment>/?.*),$\{segment}

        - id: ware
          uri: lb://gulimall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api(?<segment>/?.*),$\{segment}


        - id: member
          uri: lb://gulimall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api(?<segment>/?.*),$\{segment}



        - id: oss
          uri: lb://thired
          predicates:
            - Path=/api/thired/**
          filters:
            - RewritePath=/api/thired(?<segment>/?.*),$\{segment}



        - id: admin_route
          #        负载均衡，后为nacos服务名
          uri: lb://renren-fast
          #          断言地址是否是已/api/开头
          predicates:
            - Path=/api/**
          #            过滤器，将路径重写
          #          /api/**  ->   /renren-fast/***
          filters:
            - RewritePath=/api(?<segment>/?.*),/renren-fast$\{segment}

        - id: nginx_auth
          uri: lb://auth-server
          predicates:
            #nginx代理给网关会丢掉host信息,配置nginx文件设置上host
            - Host=auth.gulimall.com

        - id: nginx_car
          uri: lb://gulimall-car
          predicates:
            #nginx代理给网关会丢掉host信息,配置nginx文件设置上host
            - Host=car.gulimall.com


        - id: nginx_order
          uri: lb://gulimall-order
          predicates:
            #nginx代理给网关会丢掉host信息,配置nginx文件设置上host
            - Host=order.gulimall.com


        - id: nginx_search
          uri: lb://gulimall-search
          predicates:
            #nginx代理给网关会丢掉host信息,配置nginx文件设置上host
            - Host=search.gulimall.com

        - id: nginx_index
          uri: lb://gulimall-product
          predicates:
            #nginx代理给网关会丢掉host信息,配置nginx文件设置上host
            - Host=**.gulimall.com,gulimall.com






  application:
    name: gulimall-gateway
server:
  port: 88


