server:
  port: 1000

spring:
  application:
    name: gulimall-seckill
  redis:
    host: 192.168.182.128
  task:
    execution:
      pool:
        core-size: 8
        max-size: 10
        queue-capacity: 1000
  session:
    store-type: redis
  main:
    allow-circular-references: true

