server:
  port: 100
spring:
  main:
    allow-circular-references: true
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.182.128:8333
        port: 8111
      log:
        dir: I://


