spring:
  application:
    name: gulimall-car
  redis:
    host: 192.168.182.128
  session:
    store-type: redis
  thymeleaf:
    mode: HTML
    servlet:
      content-type: text/html
  main:
    allow-circular-references: true
  cloud:
    sentinel:
      transport:
        dashboard: 192.168.182.128:8333
        port: 8111
      log:
        dir: I://
      eager: true
server:
  port: 800

gulimall:
  thread:
    core-size: 20
    maximum-pool-size: 200
    keep-alive-time: 15
    queue-size: 10000

